# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""The status vocabulary a specialist reports and a caller keys on.

These strings are the wire contract between an agent that does something and
whoever is watching. They survive the A2A boundary as text, so a specialist
written on another framework produces them without importing anything from
here, and a caller matches on them without knowing which agent answered.

Kept separate from the mechanism that produces them (``app/agents/gating.py``)
and from the code that scans for them (``app/agents/reporting.py``,
``app/cluster/cases.py``), because all three have to agree and none of them
owns the list.

This module is what remains of ``app/agents/contracts.py``. The typed payload
models that used to live alongside it were deleted when peers became
sub-agents: ``transfer_to_agent`` carries no arguments, so there is nothing
left for a per-peer request model to describe. See
``docs/design-decisions.md``.
"""

from __future__ import annotations

# --- The approval vocabulary --------------------------------------------------
#
# Three strings, and they are as much a part of the wire contract as any field
# below: a caller keys its business workflow on them, and a specialist written
# on another framework produces them without importing anything from here.

AWAITING_APPROVAL = "awaiting_approval"
"""Returned INSTEAD of performing an action, while a human is being asked.

Nothing has happened. The task is suspended in ``TASK_STATE_AUTH_REQUIRED``
and the proposal a reviewer sees is generated by ADK from the pending call
itself -- see ``app/agents/gating.py``."""

REFUSED = "refused"
"""Returned when a human was asked and declined. Also not an effect."""

NEEDS_INPUT = "needs_input"
"""Returned INSTEAD of guessing: the request is ambiguous and only the user can
resolve it. Distinct from :data:`AWAITING_APPROVAL` because nobody has been
proposed — there is no effect to approve, a required *input* is missing. The
answer is a corrected request, not a decision on a case."""

NEEDS_CONFIRMATION = "needs_confirmation"
"""Returned INSTEAD of proceeding with something unusual enough to be worth a
second look. Also not an approval: the action has no side effect, so re-running
it after the user says yes costs nothing, and there is nothing to record for
audit. It exists to stop a misplaced decimal point becoming a confident
answer."""

#: Statuses meaning "a human has to answer before this can continue". A
#: specialist returning one of these has done nothing and is asking a question;
#: every agent between it and the user must relay that question rather than
#: answer it. `app/agents/reporting.py` is what makes them survive the A2A text
#: boundary intact, at any depth.
NEEDS_USER: frozenset[str] = frozenset({NEEDS_INPUT, NEEDS_CONFIRMATION})

PUBLISHED = "published"
"""A gated write happened (``app/agents/math/tools.py``)."""

EXECUTED = "executed"
"""A gated read happened (``app/agents/trades/tools.py``)."""

CONVERTED = "converted"
"""A gated conversion happened (``app/agents/currency/tools.py``).

What is gated here is *issuing the number*, not moving money: a crypto figure
quoted off a frozen table is a price for an asset that moves by the hour, and
once it has left this system it is indistinguishable from a live quote. A human
authorises the quote before it is produced; this status says one did."""

#: Every status meaning "the gated effect actually happened". The caller scans a
#: specialist's reply for one of these and then checks the values against the
#: approved proposal (``app.cluster.cases.find_execution``); a status outside
#: this set is not treated as confirmation, so a new gated action MUST add its
#: status here or its executions are reported as `approved_not_confirmed`.
#:
#: Three spellings rather than one because the status names the effect, and
#: "published" is not a truthful description of running a query or of quoting a
#: price. The set is the seam that lets each specialist say what it did while
#: the caller stays generic.
EFFECT_PERFORMED: frozenset[str] = frozenset({PUBLISHED, EXECUTED, CONVERTED})
